config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :topics do
    resources :posts
  end
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
    
    end
    def create 
        @topic = Topic.find(params[:topic_id])
        @post = @topic.posts.create(post_params)
        redirect_to @topic
    end

    def destroy
        @topic = Topic.find(params[:topic_id])
        @post = @topic.posts.find(params[:id])
        @post.destroy
        redirect_to topic_path(@topic)
    end
    private
        def post_params
            params.require(:post).permit(:title, :text)
        end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    def new

    end

    def create
        @topic = Topic.new(topic_params)

        @topic.save
        redirect_to @topic
    end

    def edit
        @topic = Topic.find(params[:id])
    end

    def update
        @topic = Topic.find(params[:id])

        
            render 'edit'
    end

    def destroy
        @topic = Topic.find(params[:id])
        @topic.destroy

        redirect_to topics_path
    end

    def show
        @topic = Topic.find(params[:id])
    end

    def index
        @topics = Topic.all
    end
    

end

private
    def topic_params
        params.require(:topic).permit(:name, :description, :isModerated)
    end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @topics = Topic.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toppy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/post.html.erb
<p>posts</p>

app/views/posts/posts.html.erb
<p>posts</p>

app/views/topics/edit.html.erb
<h1>Edit the Topic</h1>
 
<%= form_for :topic, url: topic_path(@topic), method: :patch do |f| %>
 
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@topic.errors.count, "error") %> prohibited
        this topicfrom being saved:
      </h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<body class = "background">
<h1>Topic Admin Page</h1>
 
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Moderated</th>
  </tr>
 
  <% @topics.each do |topic| %>
    <tr>
      <td><%= topic.name %></td>
      <td><%= topic.description %></td>
      <td><%= topic.isModerated %></td>
      <td><%= link_to 'Show', topic_path(topic) %></td>
      <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
      <td><%= link_to 'Destroy',
                                  topic_path(topic),
                                  method: :delete,
                                  data: {confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
</body>

app/views/topics/new.html.erb
<body class = "background">
<h1>New Topic</h1>
<%= form_for :topic, url: topics_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
</body>

app/views/topics/show.html.erb
<!DOCTYPE html>

<html>

<body class = "background">
	<div class="topBar">
		<h1>Toppy</h1>
		<h2><%= @topic.name %></h2>
		<h3><%= @topic.description %> </h3>
	</div>

	<% @topic.posts.each do |post| %>
	<div class="posts">
		<div class="title">
			<p>
				<%= post.title %>
			</p>
		</div>

		<div class="text">
			<p>
				<%= post.text %>
			</p>
		</div>
	</div>
	<% end %>

	<div class=form>
		<h2>Add a Post</h2>
		<%= form_for([@topic, @topic.posts.build]) do |f| %>
		<p>
			<%= f.label :title %> <br>
			<%= f.text_field :title %>
		</p>
		<p>
			<%= f.label :text %><br>
			<%= f.text_area :text%>
		</p>
		<p>
			<%= f.submit %>
		</p>
		<% end %>
		<div class ="topicList">
			<%= link_to 'Topic List', topics_path %>
		</div>
	</div>
</body>
</html>

app/views/topics/topics.html.erb
<!DOCTYPE html>

<html>

<p>Topics</p>
<p>
    <strong>Title:</strong>
    <%= @article.name %>
</p>

<p>
    <strong>Text:</strong>
    <%= @article.description %>
</p>

</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>

<html>
<body class ="background">
	<div class="topBar">
		<h1>Toppy</h1>
		<div class="links">
			<p>
				<% @topics.each do |topic| %>
						<%= link_to topic.name, topic_path(topic) %>
						&nbsp;
			  <% end %>
			</p>
		</div>
	</div>
	<div class ="home">
		<h2>Welcome to Toppy!</h2>
			<p>This site is for discussion about topics. Jump on in and start talking!</p>

		<div class = "newTopic">
			<%= link_to 'New', "topics/new/" %>
		</div>
	</div>

</body>
</html>